Resources: 
  myEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: gateway-activations-test
      ImageId: ami-05c1fa8df71875112
      InstanceType: t2.small      
      UserData: !Base64 |
        #!/bin/bash -ex
        sudo apt-get update
        sudo apt-get install -y nginx 
        sudo apt-get update -yqq && sudo apt-get install -yqq ca-certificates git gcc make wget mc curl sendmail
        sudo apt install php-dev
        sudo apt-get update -yqq && sudo apt-get install -yqq php7.3-pgsql php7.3-mysql php7.3-sqlite3 php7.3-opcache php7.3-common php7.3-mbstring php7.3-zip php7.3-soap php7.3-cli php7.3-intl php7.3-json php7.3-xsl php7.3-imap php7.3-ldap php7.3-curl php7.3-xml php7.3-gd php7.3-dev php7.3-fpm php7.3-soap php7.3-bcmath
        sudo apt-get install pkg-config && pecl install mongodb && echo "extension=mongodb.so" > /etc/php/7.3/cli/conf.d/ext-mongodb.ini && echo "extension=mongodb.so" > /etc/php/7.3/fpm/conf.d/ext-mongodb.ini && apt-get install -y -q --no-install-recommends ssmtp
        usermod -aG www-data www-data
        sudo apt-get install -y curl
        sudo apt-get install -y docker
        curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/bin/ --filename=composer
      Tags:
        - Key: Name
          Value: gateway-activations-test
