Resources: 
  myEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: gateway-activations-test
      ImageId: ami-05c1fa8df71875112
      InstanceType: t2.small      
      UserData: !Base64 |
        #!/bin/bash -ex
        sudo apt-get update
        sudo apt-get install -y nginx 
        sudo apt-get update -yqq && sudo apt-get install -yqq ca-certificates git gcc make wget mc curl sendmail
        sudo apt install php-dev
        sudo apt-get update -yqq && sudo apt-get install -yqq php7.2-pgsql php7.2-mysql php7.2-sqlite3 php7.2-opcache php7.2-common php7.2-mbstring php7.2-zip php7.2-soap php7.2-cli php7.2-intl php7.2-json php7.2-xsl php7.2-imap php7.2-ldap php7.2-curl php7.2-xml php7.2-gd php7.2-dev php7.2-fpm php7.2-soap php7.2-bcmath
        sudo apt-get install pkg-config && pecl install mongodb && echo "extension=mongodb.so" > /etc/php/7.2/cli/conf.d/ext-mongodb.ini && echo "extension=mongodb.so" > /etc/php/7.2/fpm/conf.d/ext-mongodb.ini && apt-get install -y -q --no-install-recommends ssmtp
        usermod -aG www-data www-data
        sudo apt-get install -y curl
        curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/bin/ --filename=composer
      Tags:
        - Key: Name
          Value: gateway-activations-test
